name: Deploy Laravel to AnyHost

on:
  push:
    branches:
      - master  # atau branch yang Anda pilih untuk deploy otomatis

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Ganti dengan versi PHP yang sesuai dengan hosting Anda

      - name: Install Composer Dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --no-dev --optimize-autoloader

      # - name: Run Laravel migrations (optional)
      #   run: |
      #     php artisan migrate --force

      # - name: Upload to AnyHost via FTP
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      #   with:
      #     server: ${{ secrets.FTP_SERVER }}
      #     username: ${{ secrets.FTP_USERNAME }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     local-dir: ./  # Path ke folder Laravel Anda
      #     server-dir: /public_html1/  # Path ke direktori tujuan di server AnyHost
      #     port: 21
        # with:
        #   ftp-server: ${{ secrets.FTP_SERVER }}
        #   ftp-username: ${{ secrets.FTP_USERNAME }}
        #   ftp-password: ${{ secrets.FTP_PASSWORD }}
        #   local-dir: ./  # Path ke folder Laravel Anda
        #   server-dir: /public_html/  # Path ke direktori tujuan di server AnyHost

      - name: Clear cache (optional)
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
