name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Install PHP, Composer, dan ekstensi yang dibutuhkan
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3' # Sesuaikan dengan versi PHP Laravel Anda
        extensions: mbstring, bcmath, intl, pdo, mysql

    # Step 3: Install dependencies Laravel
    - name: Install Dependencies
      run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

    # Step 4: Run Tests
    - name: Run Tests
      env:
        APP_ENV: testing
      run: ./vendor/bin/phpunit

    # Deploy to server
    - name: Deploy to AnyHost via SSH
      env:
        HOST: ${{ secrets.ANYHOST_SSH_HOST }}
        USER: ${{ secrets.ANYHOST_SSH_USER }}
        KEY: ${{ secrets.ANYHOST_SSH_KEY }}
      run: |
        echo "$KEY" > private_key.pem
        chmod 600 private_key.pem
        rsync -avz -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" --exclude 'node_modules' --exclude '.git' ./ $USER@$HOST:/path/to/your/app
        ssh -i private_key.pem -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
          cd /path/to/your/app
          composer install --no-dev
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
        EOF